### ISSUE TITLE
Verify Command doesn't work.

### ISSUE THREAD

**Issue by Zerriss** [1etho/VelocityVerify#1]
Hello,
I configured the plugin completely, also the Bot is completely online, but if you do /verify, it shows "An error occurred while running this command."

Here is the log, when I type the command:

[21:33:38 INFO]: Exception occurred while running command for Zwaewis
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command verify for [connected player] Zwaewis (/87.123.245.128:17730)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command verify for [connected player] Zwaewis (/87.123.245.128:17730)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[velocity.jar:3.1.2-SNAPSHOT (git-2fe50bed-b115)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-2fe50bed-b115)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more
Caused by: java.lang.NullPointerException: Cannot read field "statement" because "com.etho.discordlink.utils.sql.SqlConnection.instance" is null
        at com.etho.discordlink.utils.sql.SqlConnection.isVerified(SqlConnection.java:96) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:56) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:20) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.1.2-SNAPSHOT (git-2fe50bed-b115)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-2fe50bed-b115)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[velocity.jar:3.1.2-SNAPSHOT (git-2fe50bed-b115)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-2fe50bed-b115)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more

**Comment by HiTimi2007** [comment]
When do you help me?

**Comment by 1etho** [comment]
The SQL server isn't initializing, Make sure your config section for the SQL information is empty - I don't think this project actually ever implemented Remote SQL

**Comment by Zerriss** [comment]
Now it says this:

[12:02:06 INFO]: Exception occurred while running command for Zerriss
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command verify for [connected player] Zerriss (/87.123.245.127:12423)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command verify for [connected player] Zerriss (/87.123.245.127:12423)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more
Caused by: java.lang.NoClassDefFoundError: com/loohp/interactivechat/libs/org/apache/commons/lang3/RandomStringUtils
        at com.etho.discordlink.VerifyCode.generate(VerifyCode.java:103) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:65) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:20) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more
Caused by: java.lang.ClassNotFoundException: com.loohp.interactivechat.libs.org.apache.commons.lang3.RandomStringUtils
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:85) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:62) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at com.etho.discordlink.VerifyCode.generate(VerifyCode.java:103) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:65) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:20) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more

**Comment by FireSepicHub-14** [comment]
I'm using Release 1.1, but when I use the / verify command, it says'An error occurred while running this command.'And I get the following error: As a result, the command is not executed.
```
[21:17:01 INFO]: Exception occurred while running command for Sou2014
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command verify for [connected player] Sou2014 (/192.168.1.249:58872)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command verify for [connected player] Sou2014 (/192.168.1.249:58872)
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
Caused by: java.lang.NoClassDefFoundError: com/loohp/interactivechat/libs/org/apache/commons/lang3/RandomStringUtils
	at com.etho.discordlink.VerifyCode.generate(VerifyCode.java:103) ~[?:?]
	at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:65) ~[?:?]
	at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:20) ~[?:?]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.loohp.interactivechat.libs.org.apache.commons.lang3.RandomStringUtils
	at com.etho.discordlink.VerifyCode.generate(VerifyCode.java:103) ~[?:?]
	at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:65) ~[?:?]
	at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:20) ~[?:?]
	at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity-3.1.2-153.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 3 more

```
