### ISSUE TITLE
Verify command bugs out

### ISSUE THREAD

**Issue by BurkenDev** [1etho/VelocityVerify#4]
Missing class when running /verify inside minecraft, please fix:

[00:22:18 INFO]: Exception occurred while running command for <redacted>
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command verify for [connected player] <redacted> (/<redacted>)
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command verify for [connected player] <redacted> (/<redacted>)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:245) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:272) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.NoClassDefFoundError: com/loohp/interactivechat/libs/org/apache/commons/lang3/RandomStringUtils
        at com.etho.discordlink.VerifyCode.generate(VerifyCode.java:103) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:65) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:20) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:228) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:272) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.ClassNotFoundException: com.loohp.interactivechat.libs.org.apache.commons.lang3.RandomStringUtils
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.etho.discordlink.VerifyCode.generate(VerifyCode.java:103) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:65) ~[?:?]
        at com.etho.discordlink.command.VerifyCommand.execute(VerifyCommand.java:20) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:228) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:272) ~[velocity.jar:3.3.0-SNAPSHOT (git-75d6dcc1-b371)]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more

**Comment by 7hatGuyAJ** [comment]
I also have this issue.

Velocity 3.4.0-SNAPSHOT
